from peewee import *
from models import BaseModel

class PlayerGeneralAdvancedTotals(BaseModel):
    season_id = CharField(null=True)  # added in at the end
    player_id = IntegerField(null=True)
    player_name = CharField(null=True)
    team_id = IntegerField(null=True)
    team_abbreviation = CharField(null=True)
    age = IntegerField(null=True)
    gp = IntegerField(null=True)
    w = IntegerField(null=True)
    l = IntegerField(null=True)
    w_pct = FloatField(null=True)
    min = FloatField(null=True)
    off_rating = FloatField(null=True)
    def_rating = FloatField(null=True)
    net_rating = FloatField(null=True)
    ast_pct = FloatField(null=True)
    ast_to = FloatField(null=True)
    ast_ratio = FloatField(null=True)
    oreb_pct = FloatField(null=True)
    dreb_pct = FloatField(null=True)
    reb_pct = FloatField(null=True)
    tm_tov_pct = FloatField(null=True)
    efg_pct = FloatField(null=True)
    ts_pct = FloatField(null=True)
    usg_pct = FloatField(null=True)
    pace = FloatField(null=True)
    pie = FloatField(null=True)
    fgm = FloatField(null=True)
    fga = FloatField(null=True)
    fgm_pg = FloatField(null=True)
    fga_pg = FloatField(null=True)
    fg_pct = FloatField(null=True)
    gp_rank = IntegerField(null=True)
    w_rank = IntegerField(null=True)
    l_rank = IntegerField(null=True)
    w_pct_rank = IntegerField(null=True)
    min_rank = IntegerField(null=True)
    off_rating_rank = IntegerField(null=True)
    def_rating_rank = IntegerField(null=True)
    net_rating_rank = IntegerField(null=True)
    ast_pct_rank = IntegerField(null=True)
    ast_to_rank = IntegerField(null=True)
    ast_ratio_rank = IntegerField(null=True)
    oreb_pct_rank = IntegerField(null=True)
    dreb_pct_rank = IntegerField(null=True)
    reb_pct_rank = IntegerField(null=True)
    tm_tov_pct_rank = IntegerField(null=True)
    efg_pct_rank = IntegerField(null=True)
    ts_pct_rank = IntegerField(null=True)
    usg_pct_rank = IntegerField(null=True)
    pace_rank = IntegerField(null=True)
    pie_rank = IntegerField(null=True)
    fgm_rank = IntegerField(null=True)
    fga_rank = IntegerField(null=True)
    fgm_pg_rank = IntegerField(null=True)
    fga_pg_rank = IntegerField(null=True)
    fg_pct_rank = IntegerField(null=True)
    cfid = IntegerField(null=True)
    cfparams = CharField(null=True)

    class Meta:
        db_table = 'player_general_advanced_totals'